#!/bin/sh


# colors %_% so sexYXyyyXyy
alias \
				ls='ls -hN --color=auto' \
				la='ls -a' \
				ll='ls -ll' \
				lla='ls -lla' \
				grep='grep --color=auto' \
				diff='diff --color=auto' \
				ccat='highlight --out-format=ansi'
# so hard to write

alias \
				sudov='sudo -e ' \
				zdot='~/.config/zsh' \
				cls='clear' \
				q='exit' \
				handbrake='ghb' \
				p='sudo pacman'	\
				f='$FILE' \
				v='$EDITOR' \
				b='$BROWSER'

# Locations
alias \
				config="$XDG_CONFIG_HOME" \
				desktop="$HOME/Desktop"

# bruh some shit happened to me don't question it
[ -x "$(command -v trash)" ] && alias rm="trash"

# lf
[ -x "$(command -v trash)" ] && alias rm="trash"

# fixing cfg loc
[ -x "$(command -v nvidia-settings)" ] && alias nvidia-settings="nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings"

#lf wrapper 
[ -x "$(command -v lfub)" ] && alias lf="lfub" \
# Other

alias \
				run-java='function lol() {javac "$1.java" && java "$1";unset -f lol}; lol' \
				fping='function boi() {ping -O "$1" | sed "s/.*no answer yet.*/Request timeout/g";unset -f boi}; boi'

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
[ -x "$(command -v exa)" ] && alias ls="exa --icons"
