#!/bin/zsh
#
#
#


# autosuggestions setup
bindkey '^ ' autosuggest-accept # complets on ctrl + space

# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# fzf on history
bindkey "^?" backward-delete-char
histfzf() { tac $HISTFILE | fzf; zle redisplay }
zle -N histfzf
bindkey '^f' histfzf
